server:
  port: 8081

spring:
  application:
    name: log-alert
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/alertsdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  log-alert:
    alert-threshold-ms: 4
    table-rows-writeoff-count: 1000

